baseurl: "https://shaunak-phadnis.github.io/"  # please update this to your actual URL
languageCode: "en-us"
title: "Shaunak Phadnis"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "â†©" 
  
  
permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

 
menu: 
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Output
      url: "/output/"
      weight: 2
    - name: Teaching
      url: "/teaching/"
      weight: 3
    - name: About
      url: "/about/"
      weight: 4

   # - name: Subscribe
    #  url: "index.xml"

params:
  description: ""
  footer: "&copy; Shaunak Phadnis {Year} *built from* [x-min theme](https://github.com/yihui/hugo-xmin) | [Google Scholar](https://scholar.google.com/citations?user=gvn-fXAAAAAJ&hl=en) | [LinkedIn](https://www.linkedin.com/in/shaunak-phadnis-a09333214/)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
